# Generated by Django 4.2.9 on 2024-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_store_data_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_data',
            name='store_geolocation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store_data',
            name='store_location',
            field=models.CharField(max_length=200),
        ),
    ]
